spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/v1/student/**
        - id: school-service
          uri: lb://school-service
          predicates:
            - Path=/v1/school/**
      discovery:
        locator:
          enabled: true
server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  zipkin:
    tracing:
      endpoint: http://localhost:9411
  tracing:
    enabled: true
    sampling:
      probability: 1.0

